version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./scraper/data:/app/scraper/data
      - ./history.db:/app/backend/history.db
